#!/usr/bin/env bash

export CONTECO_LABEL="package.ksqldb - ModEco"
export CONTECO_DESCRIPTION="The ModEco ksqldb module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="ksqldb"
export CONTECO_TAG="v1.0.0"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
