#!/usr/bin/env bash

export CONTECO_LABEL="package.ksqldb - ModEco"
export CONTECO_DESCRIPTION="The ModEco ksqldb module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="ksqldb"
export CONTECO_TAG="0.12.0"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
