---
version: '3'
services:

# START SERVICE ksqldb-server.base
  ksqldb-server:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.ksqldb-server.base:0.7.0
    environment: ['KSQL_BOOTSTRAP_SERVERS=${KSQLDB_KSQL_BOOTSTRAP_SERVERS}','KSQL_KSQL_SERVICE_ID=${KSQLDB_KSQL_KSQL_SERVICE_ID}'${KSQLDB_MODE}]
    command: []
    volumes: []
    ports: [${KSQLDB_PORTS}]
    networks: [package_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${KSQLDB_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${KSQLDB_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${KSQLDB_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${KSQLDB_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${KSQLDB_DEPLOY_LABELS}]
# END SERVICE ksqldb-server.base

volumes: {}
networks: {package_overlay: { external: true }}
