#!/usr/bin/env bash


prefix="package_ksqldb_$2"

if [[ "package_ksqldb_ksqldb_ksql_server_queries_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ksqldb_ksqldb_ksql_server_queries_volume
	fi
	
